export type MissionStatus = "available" | "classified" | "locked";

export type MissionMeta = {
  id: string;
  number: string; // displayed as "01", "02"...
  codename: string;
  title: string;
  logline: string; // narrative hook — first line of the scene
  status: MissionStatus;
  route?: string;
  duration?: string;
  tone?: string;
  // Archival metadata — feels like a case file
  location?: string;
  year?: string;
  category?: string;
  /** Single primary theme tag for Reading Room filtering. */
  theme?: string;
  difficulty?: 1 | 2 | 3 | 4 | 5;
  // Reserved for future creator-published cases
  creator?: string;
  version?: string;
};

export const MISSIONS: MissionMeta[] = [
  {
    id: "mission-01",
    number: "01",
    codename: "The Release",
    title: "The Release",
    logline:
      "Twelve minutes before the boardroom. The model is ready. The memo is not.",
    status: "available",
    duration: "20–40 min",
    tone: "Tense · Suspended",
    location: "San Francisco",
    year: "2024",
    category: "Business",
    theme: "Truth",
    difficulty: 3,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-02",
    number: "02",
    codename: "Black Site",
    title: "Black Site",
    logline:
      "You are the prosecutor's last witness. You no longer remember which side you came in on.",
    status: "available",
    duration: "20–40 min",
    tone: "Claustrophobic · Cold",
    location: "Undisclosed",
    year: "2019",
    category: "Justice",
    theme: "Conscience",
    difficulty: 4,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-03",
    number: "03",
    codename: "Lazarus",
    title: "Lazarus",
    logline:
      "The capsule is six hours from re-entry. The pilot has been dead for nine.",
    status: "available",
    duration: "20–40 min",
    tone: "Vast · Quiet",
    location: "Low Earth Orbit",
    year: "2031",
    category: "Frontier",
    theme: "Duty",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-04",
    number: "04",
    codename: "The Vote",
    title: "The Vote",
    logline:
      "A senator on the night of a war authorization.",
    status: "available",
    duration: "20–40 min",
    tone: "Civic · Heavy",
    location: "Washington, D.C.",
    year: "2003",
    category: "Politics",
    theme: "Power",
    difficulty: 4,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-05",
    number: "05",
    codename: "Code Black",
    title: "Code Black",
    logline:
      "Pay the people who did this, or watch the monitors. You have until the next alarm.",
    status: "available",
    duration: "20–40 min",
    tone: "Clinical · Under siege",
    location: "Meridian General Hospital",
    year: "2025",
    category: "Medical",
    theme: "Crisis",
    difficulty: 4,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-06",
    number: "06",
    codename: "Recant",
    title: "Recant",
    logline:
      "The front page is being held. The accusation that started a reckoning was a lie. You have until midnight.",
    status: "available",
    duration: "20–40 min",
    tone: "Moral · After hours",
    location: "Newsroom, investigations desk",
    year: "Present day",
    category: "Media",
    theme: "Truth",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-07",
    number: "07",
    codename: "Spillway",
    title: "Spillway",
    logline:
      "Open the gate and the parish drowns by dawn. Hold it and the city might. The call is yours, now.",
    status: "available",
    duration: "20–40 min",
    tone: "Procedural · 3 a.m. dread",
    location: "Carrow River control station",
    year: "Flood season",
    category: "Crisis",
    theme: "Crisis",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-08",
    number: "08",
    codename: "Eighty Names",
    title: "Eighty Names",
    logline:
      "Your oldest friend softened the number. The device is in the field. The records request is pending.",
    status: "available",
    duration: "20–40 min",
    tone: "Intimate · Late-night thriller",
    location: "Veyra Medical, empty office",
    year: "Present day",
    category: "Medical",
    theme: "Loyalty",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-09",
    number: "09",
    codename: "The Interpreter",
    title: "The Interpreter",
    logline:
      "The other side's interpreter softened the clause. The convoy moves at first light. You alone heard it.",
    status: "available",
    duration: "20–40 min",
    tone: "Hushed · Political thriller",
    location: "Besieged city, ceasefire room",
    year: "1995",
    category: "Conflict",
    theme: "Conscience",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-10",
    number: "10",
    codename: "The Checkpoint",
    title: "The Checkpoint",
    logline:
      "One permit before the gate closes at dawn. The sergeant will not tell you which child gets it.",
    status: "available",
    duration: "20–40 min",
    tone: "Freezing · Hushed dread",
    location: "Voryn Pass border crossing",
    year: "Late winter",
    category: "Conflict",
    theme: "Conscience",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-11",
    number: "11",
    codename: "The Holdout",
    title: "The Holdout",
    logline:
      "Eleven jurors are ready to convict. The foreman's pencil is over the pad. The fan keeps stuttering.",
    status: "available",
    duration: "20–40 min",
    tone: "Sweltering · Civic dread",
    location: "Halsworth County Courthouse, Jury Room 4B",
    year: "Present day",
    category: "Justice",
    theme: "Conscience",
    difficulty: 4,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-12",
    number: "12",
    codename: "The Glitch",
    title: "The Glitch",
    logline:
      "Four objects on the new array. The red phone is silent. The doctrine clock has three minutes left.",
    status: "available",
    duration: "20–40 min",
    tone: "Buried · Humming dread",
    location: "Voskaya Early-Warning Command, sub-level 4",
    year: "Late October",
    category: "Defense",
    theme: "Duty",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-13",
    number: "13",
    codename: "The Pursuit",
    title: "The Pursuit",
    logline:
      "He went into the river after the boy. He came up into the gaslight. You have hunted him for sixteen years.",
    status: "available",
    duration: "20–40 min",
    tone: "Rain · Gaslight · Held breath",
    location: "Saint-Verriere Dock, Halverin",
    year: "Late autumn",
    category: "Justice",
    theme: "Conscience",
    difficulty: 4,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-14",
    number: "14",
    codename: "The Lodger",
    title: "The Lodger",
    logline:
      "A knock at curfew. A stranger on the step. Your children asleep upstairs. The patrol three minutes south.",
    status: "available",
    duration: "20–40 min",
    tone: "Candlelit · Held breath",
    location: "Number 14 Vinnerstrasse, Maerlund (under occupation)",
    year: "Year 4 of the occupation",
    category: "Conflict",
    theme: "Conscience",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-15",
    number: "15",
    codename: "The Papers",
    title: "The Papers",
    logline:
      "Two transit letters under the lamp. The leader is downstairs. Your love is three doors west. The freighter sails at five.",
    status: "available",
    duration: "20–40 min",
    tone: "Smoky · Rain · Held breath",
    location: "Upstairs at Maelin's café, Kelvras (under blockade)",
    year: "Week 11 of the Sevran blockade",
    category: "Conflict",
    theme: "Love",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-16",
    number: "16",
    codename: "The Village",
    title: "The Village",
    logline:
      "Step-off is at four-eight. The hamlet has no armed men in it. The order was given at oh-two-thirty-one on a single source.",
    status: "available",
    duration: "20–40 min",
    tone: "Dust · First light · Held breath",
    location: "Eastern edge of Korven Veld, Sevra valley",
    year: "Year 2 of Operation FERN ARC",
    category: "Conflict",
    theme: "Conscience",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
  {
    id: "mission-17",
    number: "17",
    codename: "The Rope",
    title: "The Rope",
    logline:
      "Three ropes over a cottonwood at dusk. The crowd is forty. The badge is a piece of tin. Twenty-six minutes of usable light.",
    status: "available",
    duration: "20–40 min",
    tone: "Dust · Torchlight · Held breath",
    location: "Main Street, Bremmen Hollow, Cresta Plain",
    year: "Year 8 of the town's incorporation",
    category: "Conflict",
    theme: "Conscience",
    difficulty: 5,
    creator: "House Edition",
    version: "v1.0",
  },
];
