/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoundTestRouteImport } from './routes/sound-test'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NarrationPreviewRouteImport } from './routes/narration-preview'
import { Route as MissionsLegacyRouteImport } from './routes/missions-legacy'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionIdRouteImport } from './routes/mission.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminGscVerifyRouteImport } from './routes/admin.gsc-verify'
import { Route as AdminGscRouteImport } from './routes/admin.gsc'
import { Route as AdminEvaluationRouteImport } from './routes/admin.evaluation'

const SoundTestRoute = SoundTestRouteImport.update({
  id: '/sound-test',
  path: '/sound-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrationPreviewRoute = NarrationPreviewRouteImport.update({
  id: '/narration-preview',
  path: '/narration-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsLegacyRoute = MissionsLegacyRouteImport.update({
  id: '/missions-legacy',
  path: '/missions-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionIdRoute = MissionIdRouteImport.update({
  id: '/mission/$id',
  path: '/mission/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGscVerifyRoute = AdminGscVerifyRouteImport.update({
  id: '/admin/gsc-verify',
  path: '/admin/gsc-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGscRoute = AdminGscRouteImport.update({
  id: '/admin/gsc',
  path: '/admin/gsc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/admin/evaluation',
  path: '/admin/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/constitution': typeof ConstitutionRoute
  '/missions': typeof MissionsRoute
  '/missions-legacy': typeof MissionsLegacyRoute
  '/narration-preview': typeof NarrationPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-test': typeof SoundTestRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/gsc-verify': typeof AdminGscVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/mission/$id': typeof MissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/constitution': typeof ConstitutionRoute
  '/missions': typeof MissionsRoute
  '/missions-legacy': typeof MissionsLegacyRoute
  '/narration-preview': typeof NarrationPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-test': typeof SoundTestRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/gsc-verify': typeof AdminGscVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/mission/$id': typeof MissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/constitution': typeof ConstitutionRoute
  '/missions': typeof MissionsRoute
  '/missions-legacy': typeof MissionsLegacyRoute
  '/narration-preview': typeof NarrationPreviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sound-test': typeof SoundTestRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/gsc': typeof AdminGscRoute
  '/admin/gsc-verify': typeof AdminGscVerifyRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/mission/$id': typeof MissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/constitution'
    | '/missions'
    | '/missions-legacy'
    | '/narration-preview'
    | '/sitemap.xml'
    | '/sound-test'
    | '/admin/evaluation'
    | '/admin/gsc'
    | '/admin/gsc-verify'
    | '/api/chat'
    | '/api/transcribe'
    | '/mission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/constitution'
    | '/missions'
    | '/missions-legacy'
    | '/narration-preview'
    | '/sitemap.xml'
    | '/sound-test'
    | '/admin/evaluation'
    | '/admin/gsc'
    | '/admin/gsc-verify'
    | '/api/chat'
    | '/api/transcribe'
    | '/mission/$id'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/constitution'
    | '/missions'
    | '/missions-legacy'
    | '/narration-preview'
    | '/sitemap.xml'
    | '/sound-test'
    | '/admin/evaluation'
    | '/admin/gsc'
    | '/admin/gsc-verify'
    | '/api/chat'
    | '/api/transcribe'
    | '/mission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ConstitutionRoute: typeof ConstitutionRoute
  MissionsRoute: typeof MissionsRoute
  MissionsLegacyRoute: typeof MissionsLegacyRoute
  NarrationPreviewRoute: typeof NarrationPreviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoundTestRoute: typeof SoundTestRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
  AdminGscRoute: typeof AdminGscRoute
  AdminGscVerifyRoute: typeof AdminGscVerifyRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  MissionIdRoute: typeof MissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sound-test': {
      id: '/sound-test'
      path: '/sound-test'
      fullPath: '/sound-test'
      preLoaderRoute: typeof SoundTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narration-preview': {
      id: '/narration-preview'
      path: '/narration-preview'
      fullPath: '/narration-preview'
      preLoaderRoute: typeof NarrationPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions-legacy': {
      id: '/missions-legacy'
      path: '/missions-legacy'
      fullPath: '/missions-legacy'
      preLoaderRoute: typeof MissionsLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$id': {
      id: '/mission/$id'
      path: '/mission/$id'
      fullPath: '/mission/$id'
      preLoaderRoute: typeof MissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gsc-verify': {
      id: '/admin/gsc-verify'
      path: '/admin/gsc-verify'
      fullPath: '/admin/gsc-verify'
      preLoaderRoute: typeof AdminGscVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gsc': {
      id: '/admin/gsc'
      path: '/admin/gsc'
      fullPath: '/admin/gsc'
      preLoaderRoute: typeof AdminGscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/admin/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ConstitutionRoute: ConstitutionRoute,
  MissionsRoute: MissionsRoute,
  MissionsLegacyRoute: MissionsLegacyRoute,
  NarrationPreviewRoute: NarrationPreviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoundTestRoute: SoundTestRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
  AdminGscRoute: AdminGscRoute,
  AdminGscVerifyRoute: AdminGscVerifyRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  MissionIdRoute: MissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
